services:
  DB:
    image: postgres
    container_name: commefficient_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      # POSTGRES_USER: user
      # POSTGRES_PASSWORD: "#Comeff86"
      # POSTGRES_DB: commefficient_dev
    ports:
      - "5432:5432"
    # volumes:
    #   - db_data:/var/lib/postgresql/data 
    networks:
      - comm_efficient_network

  adminer:
    image: adminer
    container_name: my_adminer
    restart: always
    ports:
      - "8080:8080"  # Access Adminer on http://localhost:8080
    depends_on:
      - DB
    networks:
      - comm_efficient_network
  
  hardhat:
    build:
      context: ./contracts
    container_name: hardhat_node
    restart: always
    ports:
      - "8545:8545"
    networks:
      - comm_efficient_network
      
# Define the network for services to communicate
networks:
  comm_efficient_network:
    driver: bridge

# volumes:
#   db_data:
#   pgadmin_data:

# docker rm -f postgres-db
# docker-compose up -d --build
# docker-compose up -d

