services:
  DB:
    image: postgres
    container_name: commefficient_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "#Comeff86"
      POSTGRES_DB: commefficient_dev
    ports:
      - "5432:5432"
    # volumes:
    #   - db_data:/var/lib/postgresql/data 
    networks:
      - postgres_network

  adminer:
    image: adminer
    container_name: my_adminer
    restart: always
    ports:
      - "8080:8080"  # Access Adminer on http://localhost:8080
    depends_on:
      - DB
    networks:
      - postgres_network

  # backend:
  #   build: .
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - DB_USER=${DB_USER}
  #     - DB_HOST=DB
  #     - DB_DATABASE=${DB_DATABASE}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_DBPORT=${DB_DBPORT}
  #     - PORT=${PORT}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - hardhat_rpc_url=${hardhat_rpc_url}
  #     - network_wss_url=${network_wss_url}
  #     - 'x-api-key=${x-api-key}'
  #     - platformOperatorAddress=${platformOperatorAddress}
  #   depends_on:
  #     - DB
  #   networks:
  #     - postgres_network


# Define the network for services to communicate
networks:
  postgres_network:
    driver: bridge

# volumes:
#   db_data:
#   pgadmin_data:

# docker rm -f postgres-db
# docker-compose up -d --build
# docker-compose up -d

